// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.DBContext;

namespace TODO.Migrations
{
    [DbContext(typeof(TODODBContext))]
    [Migration("20210612184210_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("TODO.DBSchemas.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Lists");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Joker",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Avengers: Infinity War",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Joker",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TODO.DBSchemas.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<sbyte>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Tasks");

                    b.HasIndex("ListId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = (sbyte)0,
                            ListId = 1,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            Completed = (sbyte)0,
                            ListId = 1,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 3,
                            Completed = (sbyte)0,
                            ListId = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Completed = (sbyte)0,
                            ListId = 2,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Completed = (sbyte)0,
                            ListId = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Completed = (sbyte)0,
                            ListId = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Completed = (sbyte)0,
                            ListId = 3,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 8,
                            Completed = (sbyte)0,
                            ListId = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 9,
                            Completed = (sbyte)0,
                            ListId = 3,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("TODO.DBSchemas.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2021, 6, 12, 21, 42, 9, 911, DateTimeKind.Local).AddTicks(6438));

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListId = 1,
                            PassWord = "AN6NMQ6YNVrPYuFjKlrK2/2q8P+THIL4qxW9e1f1i7DWoMWpeXZPFrtfWnVJauBV3Q==",
                            UserName = "Scorsese"
                        },
                        new
                        {
                            Id = 2,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListId = 2,
                            PassWord = "AH/AEHfhG5mlXI7jd5UT9MPzLUqnKgIZFZT+3qoiEwjICuZKpiUr/ZWZ5ecnUevrtg==",
                            UserName = "Spielberg"
                        });
                });

            modelBuilder.Entity("TODO.DBSchemas.Admin", b =>
                {
                    b.HasBaseType("TODO.DBSchemas.User");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListId = 3,
                            PassWord = "AIj5w8axa7cgIDAXFYkKFeP9c1D8IJhhaFXI+70BDia8UUkdDVYHzkQ6no/B1gqfhA==",
                            UserName = "Spielberg"
                        });
                });

            modelBuilder.Entity("TODO.DBSchemas.TodoList", b =>
                {
                    b.HasOne("TODO.DBSchemas.User", "User")
                        .WithOne("List")
                        .HasForeignKey("TODO.DBSchemas.TodoList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TODO.DBSchemas.TodoTask", b =>
                {
                    b.HasOne("TODO.DBSchemas.TodoList", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("TODO.DBSchemas.Admin", b =>
                {
                    b.HasOne("TODO.DBSchemas.User", null)
                        .WithOne()
                        .HasForeignKey("TODO.DBSchemas.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TODO.DBSchemas.TodoList", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TODO.DBSchemas.User", b =>
                {
                    b.Navigation("List");
                });
#pragma warning restore 612, 618
        }
    }
}
